# crossfire wrapper parameters

serial_port: /dev/ttyUSB1

frequency: 120

# a.k.a 300 degree/s
max_roll_rate: 4.363323
max_pitch_rate: 4.363323
max_yaw_rate: 4.363323
max_thrust: 2.0

drone_mass: 0.061


# 有待进一步测量
thrust_k: 477
thrust_b: 80
