# Parameters for the loop and lemniscate trajectories at successively increasing speed
loop_z: 0.9            # Z position of loop plane [m]
loop_r: 1.5            # Radius of loop [m]
loop_v_max: 1.5      # Maximum speed achieved (approx.) [m/s]
loop_lin_a: 0.25       # Linear acceleration and deceleration of trajectory [m/s^2]
loop_clockwise: False  # Rotation direction of the quad
loop_yawing: False     # Yaw quadrotor along the circle (only for loop)