/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) hummingbird_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[4] = {5.0000000000000003e-02, -5.0000000000000003e-02, 5.0000000000000003e-02, -5.0000000000000003e-02};
static const casadi_real casadi_c1[4] = {1.7000000000000001e-01, 0., -1.7000000000000001e-01, 0.};
static const casadi_real casadi_c2[4] = {0., 1.7000000000000001e-01, 0., -1.7000000000000001e-01};

/* hummingbird_expl_vde_adj:(i0[13],i1[13],i2[4],i3[])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+35, *w6=w+38, *w7=w+42, w8, w9, w10, w11, w12, w13, w14, w15, w16, w17, *w18=w+55, *w19=w+59, *w20=w+62, *w21=w+71, *w22=w+74, w23, w24, w25, w26, w27, w28, w29, w30, *w31=w+85, *w32=w+89, *w33=w+93, *w34=w+97, *w35=w+101, *w36=w+117;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 13, w4);
  /* #5: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  w8 = w4[10];
  w9 = w4[11];
  w10 = w4[12];
  /* #6: @11 = 0 */
  w11 = 0.;
  /* #7: @12 = 0 */
  w12 = 0.;
  /* #8: @13 = 6.00319 */
  w13 = 6.0031890135200001e+00;
  /* #9: @14 = input[2][0] */
  w14 = arg[2] ? arg[2][0] : 0;
  /* #10: @15 = input[2][1] */
  w15 = arg[2] ? arg[2][1] : 0;
  /* #11: @16 = input[2][2] */
  w16 = arg[2] ? arg[2][2] : 0;
  /* #12: @17 = input[2][3] */
  w17 = arg[2] ? arg[2][3] : 0;
  /* #13: @18 = vertcat(@14, @15, @16, @17) */
  rr=w18;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  *rr++ = w17;
  /* #14: @18 = (@13*@18) */
  for (i=0, rr=w18, cs=w18; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #15: @14 = @18[0] */
  for (rr=(&w14), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #16: @15 = @18[1] */
  for (rr=(&w15), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #17: @14 = (@14+@15) */
  w14 += w15;
  /* #18: @15 = @18[2] */
  for (rr=(&w15), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #19: @14 = (@14+@15) */
  w14 += w15;
  /* #20: @15 = @18[3] */
  for (rr=(&w15), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #21: @14 = (@14+@15) */
  w14 += w15;
  /* #22: @19 = vertcat(@11, @12, @14) */
  rr=w19;
  *rr++ = w11;
  *rr++ = w12;
  *rr++ = w14;
  /* #23: @11 = 0.716 */
  w11 = 7.1600000000000008e-01;
  /* #24: @19 = (@19/@11) */
  for (i=0, rr=w19; i<3; ++i) (*rr++) /= w11;
  /* #25: @19 = @19' */
  /* #26: @3 = mac(@7,@19,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w19+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #27: @20 = @3' */
  for (i=0, rr=w20, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #28: {@19, @21, @22} = horzsplit(@20) */
  casadi_copy(w20, 3, w19);
  casadi_copy(w20+3, 3, w21);
  casadi_copy(w20+6, 3, w22);
  /* #29: @22 = @22' */
  /* #30: {@11, @12, @14} = horzsplit(@22) */
  w11 = w22[0];
  w12 = w22[1];
  w14 = w22[2];
  /* #31: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #32: @15 = (@2*@12) */
  w15  = (w2*w12);
  /* #33: @16 = @1[2] */
  for (rr=(&w16), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #34: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #35: @17 = (@16*@11) */
  w17  = (w16*w11);
  /* #36: @15 = (@15-@17) */
  w15 -= w17;
  /* #37: @21 = @21' */
  /* #38: {@17, @23, @24} = horzsplit(@21) */
  w17 = w21[0];
  w23 = w21[1];
  w24 = w21[2];
  /* #39: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #40: @25 = (@2*@24) */
  w25  = (w2*w24);
  /* #41: @15 = (@15-@25) */
  w15 -= w25;
  /* #42: @25 = @1[3] */
  for (rr=(&w25), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #43: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #44: @26 = (@25*@17) */
  w26  = (w25*w17);
  /* #45: @15 = (@15+@26) */
  w15 += w26;
  /* #46: @19 = @19' */
  /* #47: {@26, @27, @28} = horzsplit(@19) */
  w26 = w19[0];
  w27 = w19[1];
  w28 = w19[2];
  /* #48: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #49: @29 = (@16*@28) */
  w29  = (w16*w28);
  /* #50: @15 = (@15+@29) */
  w15 += w29;
  /* #51: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #52: @29 = (@25*@27) */
  w29  = (w25*w27);
  /* #53: @15 = (@15-@29) */
  w15 -= w29;
  /* #54: (@0[0] += @15) */
  for (rr=w0+0, ss=(&w15); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #55: @15 = (2.*@2) */
  w15 = (2.* w2 );
  /* #56: @14 = (-@14) */
  w14 = (- w14 );
  /* #57: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #58: @15 = (@15*@14) */
  w15 *= w14;
  /* #59: @29 = @1[0] */
  for (rr=(&w29), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #60: @30 = (@29*@12) */
  w30  = (w29*w12);
  /* #61: @15 = (@15+@30) */
  w15 += w30;
  /* #62: @30 = (@25*@11) */
  w30  = (w25*w11);
  /* #63: @15 = (@15+@30) */
  w15 += w30;
  /* #64: @30 = (@29*@24) */
  w30  = (w29*w24);
  /* #65: @15 = (@15-@30) */
  w15 -= w30;
  /* #66: @30 = (2.*@2) */
  w30 = (2.* w2 );
  /* #67: @23 = (-@23) */
  w23 = (- w23 );
  /* #68: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #69: @30 = (@30*@23) */
  w30 *= w23;
  /* #70: @15 = (@15+@30) */
  w15 += w30;
  /* #71: @30 = (@16*@17) */
  w30  = (w16*w17);
  /* #72: @15 = (@15+@30) */
  w15 += w30;
  /* #73: @30 = (@25*@28) */
  w30  = (w25*w28);
  /* #74: @15 = (@15+@30) */
  w15 += w30;
  /* #75: @30 = (@16*@27) */
  w30  = (w16*w27);
  /* #76: @15 = (@15+@30) */
  w15 += w30;
  /* #77: (@0[1] += @15) */
  for (rr=w0+1, ss=(&w15); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #78: @15 = (@16*@12) */
  w15  = (w16*w12);
  /* #79: @30 = (@2*@11) */
  w30  = (w2*w11);
  /* #80: @15 = (@15+@30) */
  w15 += w30;
  /* #81: @30 = (@16*@24) */
  w30  = (w16*w24);
  /* #82: @15 = (@15+@30) */
  w15 += w30;
  /* #83: @30 = (2.*@25) */
  w30 = (2.* w25 );
  /* #84: @30 = (@30*@23) */
  w30 *= w23;
  /* #85: @15 = (@15+@30) */
  w15 += w30;
  /* #86: @30 = (@29*@17) */
  w30  = (w29*w17);
  /* #87: @15 = (@15+@30) */
  w15 += w30;
  /* #88: @30 = (@2*@28) */
  w30  = (w2*w28);
  /* #89: @15 = (@15+@30) */
  w15 += w30;
  /* #90: @30 = (@29*@27) */
  w30  = (w29*w27);
  /* #91: @15 = (@15-@30) */
  w15 -= w30;
  /* #92: @30 = (2.*@25) */
  w30 = (2.* w25 );
  /* #93: @26 = (-@26) */
  w26 = (- w26 );
  /* #94: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #95: @30 = (@30*@26) */
  w30 *= w26;
  /* #96: @15 = (@15+@30) */
  w15 += w30;
  /* #97: (@0[3] += @15) */
  for (rr=w0+3, ss=(&w15); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #98: @15 = (2.*@16) */
  w15 = (2.* w16 );
  /* #99: @15 = (@15*@14) */
  w15 *= w14;
  /* #100: @12 = (@25*@12) */
  w12  = (w25*w12);
  /* #101: @15 = (@15+@12) */
  w15 += w12;
  /* #102: @11 = (@29*@11) */
  w11  = (w29*w11);
  /* #103: @15 = (@15-@11) */
  w15 -= w11;
  /* #104: @24 = (@25*@24) */
  w24  = (w25*w24);
  /* #105: @15 = (@15+@24) */
  w15 += w24;
  /* #106: @17 = (@2*@17) */
  w17  = (w2*w17);
  /* #107: @15 = (@15+@17) */
  w15 += w17;
  /* #108: @28 = (@29*@28) */
  w28  = (w29*w28);
  /* #109: @15 = (@15+@28) */
  w15 += w28;
  /* #110: @27 = (@2*@27) */
  w27  = (w2*w27);
  /* #111: @15 = (@15+@27) */
  w15 += w27;
  /* #112: @27 = (2.*@16) */
  w27 = (2.* w16 );
  /* #113: @27 = (@27*@26) */
  w27 *= w26;
  /* #114: @15 = (@15+@27) */
  w15 += w27;
  /* #115: (@0[2] += @15) */
  for (rr=w0+2, ss=(&w15); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #116: @18 = zeros(4x1) */
  casadi_clear(w18, 4);
  /* #117: @15 = 0 */
  w15 = 0.;
  /* #118: @19 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w19);
  /* #119: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #120: @27 = (-@27) */
  w27 = (- w27 );
  /* #121: @26 = @19[1] */
  for (rr=(&w26), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #122: @26 = (-@26) */
  w26 = (- w26 );
  /* #123: @28 = @19[2] */
  for (rr=(&w28), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #124: @28 = (-@28) */
  w28 = (- w28 );
  /* #125: @31 = horzcat(@15, @27, @26, @28) */
  rr=w31;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #126: @31 = @31' */
  /* #127: @15 = @19[0] */
  for (rr=(&w15), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #128: @27 = 0 */
  w27 = 0.;
  /* #129: @26 = @19[2] */
  for (rr=(&w26), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #130: @28 = @19[1] */
  for (rr=(&w28), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #131: @28 = (-@28) */
  w28 = (- w28 );
  /* #132: @32 = horzcat(@15, @27, @26, @28) */
  rr=w32;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #133: @32 = @32' */
  /* #134: @15 = @19[1] */
  for (rr=(&w15), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #135: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #136: @27 = (-@27) */
  w27 = (- w27 );
  /* #137: @26 = 0 */
  w26 = 0.;
  /* #138: @28 = @19[0] */
  for (rr=(&w28), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #139: @33 = horzcat(@15, @27, @26, @28) */
  rr=w33;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #140: @33 = @33' */
  /* #141: @15 = @19[2] */
  for (rr=(&w15), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #142: @27 = @19[1] */
  for (rr=(&w27), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #143: @26 = @19[0] */
  for (rr=(&w26), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #144: @26 = (-@26) */
  w26 = (- w26 );
  /* #145: @28 = 0 */
  w28 = 0.;
  /* #146: @34 = horzcat(@15, @27, @26, @28) */
  rr=w34;
  *rr++ = w15;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w28;
  /* #147: @34 = @34' */
  /* #148: @35 = horzcat(@31, @32, @33, @34) */
  rr=w35;
  for (i=0, cs=w31; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  /* #149: @15 = 0.5 */
  w15 = 5.0000000000000000e-01;
  /* #150: @6 = (@15*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #151: @18 = mac(@35,@6,@18) */
  for (i=0, rr=w18; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w35+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #152: @0 = (@0+@18) */
  for (i=0, rr=w0, cs=w18; i<4; ++i) (*rr++) += (*cs++);
  /* #153: output[0][0] = @0 */
  casadi_copy(w0, 4, res[0]);
  /* #154: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #155: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #156: @15 = 0.005 */
  w15 = 5.0000000000000001e-03;
  /* #157: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #158: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #159: @26 = 142.857 */
  w26 = 1.4285714285714286e+02;
  /* #160: @26 = (@26*@9) */
  w26 *= w9;
  /* #161: @27 = (@27*@26) */
  w27 *= w26;
  /* #162: (@5[0] += @27) */
  for (rr=w5+0, ss=(&w27); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #163: @27 = @19[0] */
  for (rr=(&w27), ss=w19+0; ss!=w19+1; ss+=1) *rr++ = *ss;
  /* #164: @27 = (@27*@26) */
  w27 *= w26;
  /* #165: @15 = (@15*@27) */
  w15 *= w27;
  /* #166: (@5[2] += @15) */
  for (rr=w5+2, ss=(&w15); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #167: @15 = -0.005 */
  w15 = -5.0000000000000001e-03;
  /* #168: @27 = @19[1] */
  for (rr=(&w27), ss=w19+1; ss!=w19+2; ss+=1) *rr++ = *ss;
  /* #169: @27 = (@15*@27) */
  w27  = (w15*w27);
  /* #170: @9 = 142.857 */
  w9 = 1.4285714285714286e+02;
  /* #171: @9 = (@9*@8) */
  w9 *= w8;
  /* #172: @27 = (@27*@9) */
  w27 *= w9;
  /* #173: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #174: @27 = @19[2] */
  for (rr=(&w27), ss=w19+2; ss!=w19+3; ss+=1) *rr++ = *ss;
  /* #175: @27 = (@27*@9) */
  w27 *= w9;
  /* #176: @15 = (@15*@27) */
  w15 *= w27;
  /* #177: (@5[1] += @15) */
  for (rr=w5+1, ss=(&w15); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #178: @35 = zeros(4x4) */
  casadi_clear(w35, 16);
  /* #179: @1 = @1' */
  /* #180: @35 = mac(@6,@1,@35) */
  for (i=0, rr=w35; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #181: @36 = @35' */
  for (i=0, rr=w36, cs=w35; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #182: {@6, @1, @0, @18} = horzsplit(@36) */
  casadi_copy(w36, 4, w6);
  casadi_copy(w36+4, 4, w1);
  casadi_copy(w36+8, 4, w0);
  casadi_copy(w36+12, 4, w18);
  /* #183: @18 = @18' */
  /* #184: {@15, @27, @8, NULL} = horzsplit(@18) */
  w15 = w18[0];
  w27 = w18[1];
  w8 = w18[2];
  /* #185: @8 = (-@8) */
  w8 = (- w8 );
  /* #186: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #187: (@5[1] += @27) */
  for (rr=w5+1, ss=(&w27); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #188: (@5[2] += @15) */
  for (rr=w5+2, ss=(&w15); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #189: @0 = @0' */
  /* #190: {@15, @27, NULL, @8} = horzsplit(@0) */
  w15 = w0[0];
  w27 = w0[1];
  w8 = w0[3];
  /* #191: (@5[0] += @8) */
  for (rr=w5+0, ss=(&w8); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #192: @27 = (-@27) */
  w27 = (- w27 );
  /* #193: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #194: (@5[1] += @15) */
  for (rr=w5+1, ss=(&w15); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #195: @1 = @1' */
  /* #196: {@15, NULL, @27, @8} = horzsplit(@1) */
  w15 = w1[0];
  w27 = w1[2];
  w8 = w1[3];
  /* #197: @8 = (-@8) */
  w8 = (- w8 );
  /* #198: (@5[1] += @8) */
  for (rr=w5+1, ss=(&w8); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #199: (@5[2] += @27) */
  for (rr=w5+2, ss=(&w27); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #200: (@5[0] += @15) */
  for (rr=w5+0, ss=(&w15); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #201: @6 = @6' */
  /* #202: {NULL, @15, @27, @8} = horzsplit(@6) */
  w15 = w6[1];
  w27 = w6[2];
  w8 = w6[3];
  /* #203: @8 = (-@8) */
  w8 = (- w8 );
  /* #204: (@5[2] += @8) */
  for (rr=w5+2, ss=(&w8); rr!=w5+3; rr+=1) *rr += *ss++;
  /* #205: @27 = (-@27) */
  w27 = (- w27 );
  /* #206: (@5[1] += @27) */
  for (rr=w5+1, ss=(&w27); rr!=w5+2; rr+=1) *rr += *ss++;
  /* #207: @15 = (-@15) */
  w15 = (- w15 );
  /* #208: (@5[0] += @15) */
  for (rr=w5+0, ss=(&w15); rr!=w5+1; rr+=1) *rr += *ss++;
  /* #209: output[0][2] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+7);
  /* #210: @15 = 6.00319 */
  w15 = 6.0031890135200001e+00;
  /* #211: @27 = 83.3333 */
  w27 = 8.3333333333333329e+01;
  /* #212: @27 = (@27*@10) */
  w27 *= w10;
  /* #213: @6 = [0.05, -0.05, 0.05, -0.05] */
  casadi_copy(casadi_c0, 4, w6);
  /* #214: @6 = @6' */
  /* #215: @6 = (@27*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w27*(*cs++));
  /* #216: @6 = @6' */
  /* #217: @1 = [0.17, 0, -0.17, 0] */
  casadi_copy(casadi_c1, 4, w1);
  /* #218: @1 = @1' */
  /* #219: @1 = (@26*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w26*(*cs++));
  /* #220: @1 = (-@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) *rr++ = (- *cs++ );
  /* #221: @1 = @1' */
  /* #222: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #223: @1 = [0, 0.17, 0, -0.17] */
  casadi_copy(casadi_c2, 4, w1);
  /* #224: @1 = @1' */
  /* #225: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #226: @1 = @1' */
  /* #227: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #228: @6 = (@15*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w15*(*cs++));
  /* #229: @1 = zeros(4x1) */
  casadi_clear(w1, 4);
  /* #230: @15 = 1.39665 */
  w15 = 1.3966480446927372e+00;
  /* #231: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #232: @9 = 1 */
  w9 = 1.;
  /* #233: @26 = sq(@16) */
  w26 = casadi_sq( w16 );
  /* #234: @27 = sq(@25) */
  w27 = casadi_sq( w25 );
  /* #235: @26 = (@26+@27) */
  w26 += w27;
  /* #236: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #237: @9 = (@9-@26) */
  w9 -= w26;
  /* #238: @26 = (@2*@16) */
  w26  = (w2*w16);
  /* #239: @27 = (@29*@25) */
  w27  = (w29*w25);
  /* #240: @26 = (@26-@27) */
  w26 -= w27;
  /* #241: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #242: @27 = (@2*@25) */
  w27  = (w2*w25);
  /* #243: @10 = (@29*@16) */
  w10  = (w29*w16);
  /* #244: @27 = (@27+@10) */
  w27 += w10;
  /* #245: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #246: @19 = horzcat(@9, @26, @27) */
  rr=w19;
  *rr++ = w9;
  *rr++ = w26;
  *rr++ = w27;
  /* #247: @19 = @19' */
  /* #248: @9 = (@2*@16) */
  w9  = (w2*w16);
  /* #249: @26 = (@29*@25) */
  w26  = (w29*w25);
  /* #250: @9 = (@9+@26) */
  w9 += w26;
  /* #251: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #252: @26 = 1 */
  w26 = 1.;
  /* #253: @27 = sq(@2) */
  w27 = casadi_sq( w2 );
  /* #254: @10 = sq(@25) */
  w10 = casadi_sq( w25 );
  /* #255: @27 = (@27+@10) */
  w27 += w10;
  /* #256: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #257: @26 = (@26-@27) */
  w26 -= w27;
  /* #258: @27 = (@16*@25) */
  w27  = (w16*w25);
  /* #259: @10 = (@29*@2) */
  w10  = (w29*w2);
  /* #260: @27 = (@27-@10) */
  w27 -= w10;
  /* #261: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #262: @21 = horzcat(@9, @26, @27) */
  rr=w21;
  *rr++ = w9;
  *rr++ = w26;
  *rr++ = w27;
  /* #263: @21 = @21' */
  /* #264: @9 = (@2*@25) */
  w9  = (w2*w25);
  /* #265: @26 = (@29*@16) */
  w26  = (w29*w16);
  /* #266: @9 = (@9-@26) */
  w9 -= w26;
  /* #267: @9 = (2.*@9) */
  w9 = (2.* w9 );
  /* #268: @25 = (@16*@25) */
  w25  = (w16*w25);
  /* #269: @29 = (@29*@2) */
  w29 *= w2;
  /* #270: @25 = (@25+@29) */
  w25 += w29;
  /* #271: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #272: @29 = 1 */
  w29 = 1.;
  /* #273: @2 = sq(@2) */
  w2 = casadi_sq( w2 );
  /* #274: @16 = sq(@16) */
  w16 = casadi_sq( w16 );
  /* #275: @2 = (@2+@16) */
  w2 += w16;
  /* #276: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #277: @29 = (@29-@2) */
  w29 -= w2;
  /* #278: @22 = horzcat(@9, @25, @29) */
  rr=w22;
  *rr++ = w9;
  *rr++ = w25;
  *rr++ = w29;
  /* #279: @22 = @22' */
  /* #280: @20 = horzcat(@19, @21, @22) */
  rr=w20;
  for (i=0, cs=w19; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<3; ++i) *rr++ = *cs++;
  /* #281: @5 = mac(@20,@7,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w20+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #282: @5 = (@15*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #283: {NULL, NULL, @15} = vertsplit(@5) */
  w15 = w5[2];
  /* #284: (@1[3] += @15) */
  for (rr=w1+3, ss=(&w15); rr!=w1+4; rr+=1) *rr += *ss++;
  /* #285: (@1[2] += @15) */
  for (rr=w1+2, ss=(&w15); rr!=w1+3; rr+=1) *rr += *ss++;
  /* #286: (@1[1] += @15) */
  for (rr=w1+1, ss=(&w15); rr!=w1+2; rr+=1) *rr += *ss++;
  /* #287: (@1[0] += @15) */
  for (rr=w1+0, ss=(&w15); rr!=w1+1; rr+=1) *rr += *ss++;
  /* #288: @1 = (@13*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w13*(*cs++));
  /* #289: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #290: {@13, @15, @9, @25} = vertsplit(@6) */
  w13 = w6[0];
  w15 = w6[1];
  w9 = w6[2];
  w25 = w6[3];
  /* #291: output[0][3] = @13 */
  if (res[0]) res[0][10] = w13;
  /* #292: output[0][4] = @15 */
  if (res[0]) res[0][11] = w15;
  /* #293: output[0][5] = @9 */
  if (res[0]) res[0][12] = w9;
  /* #294: output[0][6] = @25 */
  if (res[0]) res[0][13] = w25;
  return 0;
}

CASADI_SYMBOL_EXPORT int hummingbird_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int hummingbird_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int hummingbird_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hummingbird_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int hummingbird_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void hummingbird_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void hummingbird_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void hummingbird_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int hummingbird_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int hummingbird_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real hummingbird_expl_vde_adj_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hummingbird_expl_vde_adj_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* hummingbird_expl_vde_adj_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hummingbird_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* hummingbird_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int hummingbird_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 133;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
